# Legal RAG Index Pipeline - ColBERT Legal French
#
# This pipeline builds the PLAID index for ColBERT Legal French.
#
# Usage:
#   task-tracker submit pipelines/colbert_legal_french_index.yaml

name: colbert_legal_french_index
description: Build PLAID index with ColBERT Legal French
version: "2.0"

project: legal-rag
experiment: legal_rag

defaults:
  base_dir: /data/workspace/${USER}

  # Dataset configuration
  dataset: artefactory/Argimi-Legal-French-Jurisprudence
  subset: constit
  split: train

  # Model configuration
  encoder_model: maastrichtlawtech/colbert-legal-french

  # Index configuration
  index_name: colbert_legal_french_${subset}_index
  batch_size: 1024
  accumulation_size: 32768  # 32 * 1024
  pool_factor: 1  # 1 = no pooling, higher = more compression

  # Paths
  index_dir: ${base_dir}/legal-rag/index

steps:
  - command: "python scripts/indexer.py"
    arguments:
      model: "${encoder_model}"
      dataset: "${dataset}"
      subset: "${subset}"
      split: "${split}"
      batch_size: ${batch_size}
      accumulation_size: ${accumulation_size}
      pool_factor: ${pool_factor}
      index_folder: "${index_dir}"
      index_name: "${index_name}"
    gpu_count: 1
    artifacts:
      inputs:
        - path: "${dataset}"
          type: Dataset
      outputs:
        - path: "${index_dir}/${index_name}"
          type: Dataset
